import GlobalStae from '@/context';
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Yuxastur Nutrition',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStae>
          <Navbar />
          <main className="flex min-h-screen flex-col mt-[80px] ">
            {children}
          </main>
        </GlobalStae>
      </body>
    </html>
  );
}
